# Generated by Django 3.2 on 2022-04-13 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='病人ID')),
                ('csv_id', models.IntegerField(blank=True, null=True, verbose_name='备用编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重')),
                ('diagnose', models.CharField(blank=True, max_length=50, null=True, verbose_name='诊断')),
                ('operation', models.CharField(blank=True, max_length=50, null=True, verbose_name='手术')),
                ('ventilation_mode', models.IntegerField(blank=True, choices=[(0, '喉罩'), (1, '气管插管')], default=0, null=True, verbose_name='通气方式')),
                ('nerve_block', models.IntegerField(blank=True, choices=[(0, '无'), (1, '有')], default=0, null=True, verbose_name='神经阻滞')),
                ('analgesic_pump', models.IntegerField(blank=True, choices=[(0, '无'), (1, '有')], default=0, null=True, verbose_name='镇痛泵')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sample_num', models.IntegerField(default=0, verbose_name='样本数')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='样本ID')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('diastolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('systolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('before_operation', models.IntegerField(blank=True, choices=[(0, '术前'), (1, '术后')], default=0, null=True, verbose_name='术前术后')),
                ('video', models.FileField(upload_to='mp4/', verbose_name='视频')),
                ('biology', models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='生理信号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sample', to='patient.patient', verbose_name='病人ID')),
            ],
            options={
                'verbose_name': '样本',
                'verbose_name_plural': '样本',
            },
        ),
    ]
