# Generated by Django 3.2 on 2022-04-13 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('FLACC_score', models.FloatField(blank=True, null=True, verbose_name='FLACC')),
                ('FACE_score', models.FloatField(blank=True, null=True, verbose_name='FACE')),
                ('legs_score', models.FloatField(blank=True, null=True, verbose_name='legs')),
                ('Acitivity_score', models.FloatField(blank=True, null=True, verbose_name='Acitivity')),
                ('Cry_score', models.FloatField(blank=True, null=True, verbose_name='Cry')),
                ('consolability_score', models.FloatField(blank=True, null=True, verbose_name='consolability')),
                ('VAS_score', models.FloatField(blank=True, null=True, verbose_name='VAS')),
                ('lianpu_score', models.FloatField(blank=True, null=True, verbose_name='脸谱')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sample', to='patient.sample', verbose_name='样本ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_user', to='patient.user', verbose_name='用户ID')),
            ],
        ),
    ]
