# Generated by Django 3.2 on 2022-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
