# Generated by Django 3.2 on 2022-04-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_score_npy_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='面部帧评分')),
                ('voice_score_npy_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='声音帧评分')),
                ('body_score_npy_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='肢体帧评分')),
                ('face_score', models.FloatField(blank=True, null=True, verbose_name='面部评分')),
                ('voice_score', models.FloatField(blank=True, null=True, verbose_name='声音评分')),
                ('body_score', models.FloatField(blank=True, null=True, verbose_name='肢体评分')),
                ('bio_score', models.FloatField(blank=True, null=True, verbose_name='生理评分')),
                ('all_score', models.FloatField(blank=True, null=True, verbose_name='总评分')),
                ('face_mp4_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='面部特征视频')),
                ('voice_npy_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='声音特征视频')),
                ('body_mp4_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='肢体特征视频')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AIscore_sample', to='patient.sample', verbose_name='样本ID')),
            ],
        ),
    ]
