# Generated by Django 3.2 on 2022-08-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_aiscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
