# Generated by Django 3.2 on 2022-08-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='score',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
