# Generated by Django 3.2 on 2022-09-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20220829_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-add_time',), 'verbose_name': '病人', 'verbose_name_plural': '病人'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-add_time',), 'verbose_name': '样本', 'verbose_name_plural': '样本'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-add_time',), 'verbose_name': '分数', 'verbose_name_plural': '分数'},
        ),
    ]
