# Generated by Django 3.2 on 2022-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220915_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='before_operation',
            field=models.IntegerField(blank=True, choices=[(0, '麻醉诱导前'), (1, '麻醉诱导时'), (2, '术后拔管时'), (3, '出室前')], default=0, null=True, verbose_name='手术阶段'),
        ),
    ]
