# Generated by Django 3.2 on 2022-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_sample_before_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='before_operation',
            field=models.IntegerField(blank=True, choices=[(1, '麻醉诱导前'), (2, '麻醉诱导时'), (3, '术后拔管时'), (4, '出室前')], default=1, null=True, verbose_name='手术阶段'),
        ),
    ]
