# Generated by Django 3.2 on 2022-09-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_sample_before_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='csv_id',
            field=models.IntegerField(blank=True, verbose_name='csv编号'),
        ),
    ]
