# Generated by Django 3.2 on 2023-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sample_num',
        ),
    ]
