# Generated by Django 3.2 on 2023-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20230609_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='diastolic_pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='舒张压'),
        ),
        migrations.AddField(
            model_name='score',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='心率'),
        ),
        migrations.AddField(
            model_name='score',
            name='systolic_pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='收缩压'),
        ),
    ]
