# Generated by Django 3.2 on 2023-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20230612_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
